# Generated by Django 5.0.6 on 2025-06-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discount_type',
            field=models.CharField(blank=True, choices=[('percentage', 'Percentage'), ('flat', 'Flat Amount')], help_text="Choose 'Percentage' for a percent discount or 'Flat' for a fixed amount.", max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='discount_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Enter the discount value. For percentage, input a number between 0 and 100.', max_digits=10, null=True),
        ),
    ]
