# Generated by Django 5.0.6 on 2025-06-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_item_discount_type_item_discount_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price after applying the discount.', max_digits=10, null=True),
        ),
    ]
